version: "1"
services:
  db:
    image: "postgres:13"
    container_name: "comment_and_replies_postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root123"
    ports:
      - "5438:5432"
    volumes:
      - comment_and_replies_dbdata:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    ports:
      - 6380:6379
    command: redis-server --save 60 1
    volumes:
      - redis_dbdata:/data
volumes:
  comment_and_replies_dbdata:
  redis_dbdata: